import { Component } from '@angular/core';

@Component({
  selector: 'app-competence',
  standalone: true,
  imports: [],
  templateUrl: './competence.component.html',
  styleUrl: './competence.component.css'
})
export class CompetenceComponent {

  competences=[
    {
      id:1,
      nom:"HTML",
      niveau:"expérimenté",
      image:"assets/images/svg/img1.png"
    },
    {
      id:2,
      nom:"CSS",
      niveau:"expérimenté",
      image:"assets/images/svg/img2.png"
    },
    {
      id:3,
      nom:"JavaScript",
      niveau:"intermédiaire",
      image:"assets/images/svg/img3.png"
    },
    {
      id:4,
      nom:"TypeScript",
      niveau:"expérimenté",
      image:"assets/images/svg/img4.png"
    },
    {
      id:5,
      nom:"Java",
      niveau:"expérimenté",
      image:"assets/images/svg/img5.png"
    },
    {
      id:6,
      nom:"Python",
      niveau:"expérimenté",
      image:"assets/images/svg/img6.png"
    },
    {
      id:7,
      nom:"Dart",
      niveau:"intermédiaire",
      image:"assets/images/svg/img7.png"
    },
    {
      id:8,
      nom:"javaEE",
      niveau:"expérimenté",
      image:"assets/images/svg/img8.png"
    },
    {
      id:9,
      nom:"Spring",
      niveau:"expérimenté",
      image:"assets/images/svg/img9.png"
    },
    {
      id:10,
      nom:"Flask",
      niveau:"intermédiaire",
      image:"assets/images/svg/img10.png"
    },
    {
      id:11,
      nom:"FastAPI",
      niveau:"expérimenté",
      image:"assets/images/svg/img11.png"
    },
    {
      id:12,
      nom:"Angular",
      niveau:"expérimenté",
      image:"assets/images/svg/img12.png"
    },
    {
      id:13,
      nom:"Flutter",
      niveau:"expérimenté",
      image:"assets/images/svg/img13.png"
    },
    {
      id:14,
      nom:"Tailwind",
      niveau:"expérimenté",
      image:"assets/images/svg/img14.png"
    },
    {
      id:15,
      nom:"Bootstrap",
      niveau:"expérimenté",
      image:"assets/images/svg/img15.png"
    },
    {
      id:16,
      nom:"Docker",
      niveau:"expérimenté",
      image:"assets/images/svg/img16.png"
    },
    {
      id:17,
      nom:"Git",
      niveau:"expérimenté",
      image:"assets/images/svg/img17.png"
    },
    {
      id:18,
      nom:"GitHub",
      niveau:"expérimenté",
      image:"assets/images/svg/img18.png"
    },
    {
      id:19,
      nom:"MongoDB",
      niveau:"intermédiaire",
      image:"assets/images/svg/img19.png"
    },
    {
      id:20,
      nom:"Oracle",
      niveau:"intermédiaire",
      image:"assets/images/svg/img20.png"
    },
    {
      id:21,
      nom:"MySQL",
      niveau:"expérimenté",
      image:"assets/images/svg/img21.png"
    },
    {
      id:22,
      nom:"UML",
      niveau:"expérimenté",
      image:"assets/images/svg/img22.png"
    },
    {
      id:23,
      nom:"Figma",
      niveau:"intermédiaire",
      image:"assets/images/svg/img23.png"
    },
    {
      id:24,
      nom:"Kubernetes",
      niveau:"Debutant",
      image:"assets/images/svg/img24.png"
    },
    {
      id:25,
      nom:"AWS",
      niveau:"intermédiaire",
      image:"assets/images/svg/img25.png"
    },
    {
      id:26,
      nom:"GitHub Actions",
      niveau:"intermédiaire",
      image:"assets/images/svg/img26.png"
    },]
   }
